### ISSUE TITLE
clowder.geostreams.sensors is not a function

### ISSUE THREAD

**Issue by josephmilla** [ncsa/clowderjs#2]
Execution of:

``` javascript
clowder.geostreams.sensors(auth, function(sensors){
  console.log(sensors);
});
```

Results to:

``` javascript
clowder.geostreams.sensors(auth, function(sensors){
                   ^
TypeError: clowder.geostreams.sensors is not a function
    at Object.<anonymous> (/Users/josephmilla/Desktop/test/app.js:13:20)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3
```

I believe there should be something like this:

``` javascript
exports.sensors = function(auth, callback) {
  request.get(auth.api + "/geostreams/sensors", {gzip: true}, function(err, response, body) {
    if (err) callback(err);
    try {
      callback(JSON.parse(body));
    } catch (e) {
      callback(body);
    }
  });
};

```

`GET` method in `sensors.js` is only accessible through: 

``` javascript
var sensors = require('./sensors');
sensors.get(auth, function(sensors) {});
```

as used in `cache.js`

**Comment by brock** [comment]
Sensors is a namespace, since it supports more than just `get sensors`.

You need to use the following:

```
clowder.geostreams.sensors.get(auth, function(sensors){
  console.log(sensors);
});
```
